/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideView: typeof import('./src/components/AsideView.vue')['default']
    CommentView: typeof import('./src/components/CommentView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    NewsFeedView: typeof import('./src/components/NewsFeedView.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedPostCard: typeof import('./src/components/SharedPostCard.vue')['default']
  }
}
